name: Style and Linting
on: [push]

jobs:
  lint_and_style:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install autopep8
      run: |
        python -m pip install --upgrade pip
        pip install autopep8
    - name: Install pylint
      run: |
        python -m pip install pylint
        
    - name: Fix code style issues
      run: |
        autopep8 --in-place --aggressive your_code.py

    - name: Analyze code with pylint
      run: |
        pylint your_code.py
